### ISSUE TITLE
Directory already exists

### ISSUE THREAD

**Issue by ghost** [Sonosus/kmgenerator#8]
I tried the latest version, first module went in okay but I got an error at the end of entering the second:

```
maker_site []: 
Traceback (most recent call last):
  File "fetchuuid.py", line 107, in <module>
    cookiecutter(script_path, extra_context={'maker_uuid':maker_uuid, 'maker_name':maker_name, 'maker_desc':maker_desc, 'maker_site':maker_site})
  File "/home/rsholmes/.local/lib/python3.8/site-packages/cookiecutter/main.py", line 108, in cookiecutter
    result = generate_files(
  File "/home/rsholmes/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 291, in generate_files
    project_dir, output_directory_created = render_and_create_dir(
  File "/home/rsholmes/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 223, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "Analog Output" directory already exists
```

**Comment by Sonosus** [comment]
I'll need to rewrite a significant portion of the code and move away from cookiecutter to fix this. I'm working on it.
